"""
Demo-only admin routes for resetting the demo state between visitors.

Only enabled when DEMO_MODE=true. Wipes demo-related tasks/messages and
re-runs the seed so the next walkthrough starts clean.
"""

from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException, status

from config import DEMO_MODE
from database import (
    tasks_collection,
    messages_collection,
    notifications_collection,
)
from security import get_current_user


router = APIRouter(prefix="/api/demo", tags=["demo"])


DEMO_USERS = ["mike_customer", "alice_builder", "bob_fixer", "admin"]


def _require_demo_admin(user: dict) -> None:
    if not DEMO_MODE:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Demo endpoints are disabled.",
        )
    if user.get("role") != "admin":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Admin access required.",
        )


@router.post("/reset")
async def reset_demo(
    current_user: Annotated[dict, Depends(get_current_user)],
):
    """Wipe demo tasks, messages, notifications, then re-seed."""
    _require_demo_admin(current_user)

    # Delete tasks posted by demo users OR auto-generated by the demo scrape
    task_filter = {
        "$or": [
            {"client_username": {"$in": DEMO_USERS}},
            {"tasker_username": {"$in": DEMO_USERS}},
            {"is_demo_scrape": True},
            {"source": "craigslist", "is_auto_generated": True},
        ]
    }
    tasks_result = tasks_collection.delete_many(task_filter)

    # Wipe all messages (chat) and notifications between demo users
    msg_result = messages_collection.delete_many(
        {"sender_username": {"$in": DEMO_USERS}}
    )
    notif_result = notifications_collection.delete_many(
        {"user_to_notify": {"$in": DEMO_USERS}}
    )

    # Re-seed canonical demo data
    try:
        from create_test_data import create_test_data
        create_test_data()
    except Exception as e:
        return {
            "ok": True,
            "tasks_deleted": tasks_result.deleted_count,
            "messages_deleted": msg_result.deleted_count,
            "notifications_deleted": notif_result.deleted_count,
            "reseed_warning": str(e),
        }

    return {
        "ok": True,
        "tasks_deleted": tasks_result.deleted_count,
        "messages_deleted": msg_result.deleted_count,
        "notifications_deleted": notif_result.deleted_count,
    }
